name: Ptank

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  # Triggers the workflow on push or pull request events but only for the "master" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: wget http://data.phishtank.com/data/3e93925c8e73988103061cea4c6f73326626c43cd16a594695752f8ab0e239b7/online-valid.csv.gz 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git show HEAD~1:online-valid.csv.gz > /dev/null 2>&1
          if [ $? -ne 0 ];
          then
            wget http://data.phishtank.com/data/3e93925c8e73988103061cea4c6f73326626c43cd16a594695752f8ab0e239b7/online-valid.csv.gz
          else
            git rm online-valid.csv.gz
            git add .
            git commit -m "Removed obsolate files"
            git push
            wget http://data.phishtank.com/data/3e93925c8e73988103061cea4c6f73326626c43cd16a594695752f8ab0e239b7/online-valid.csv.gz
            git add -A
            git commit -m "Update online-valid.csv.tgz"
            git push
          fi  
